name : "INTEL"
dataset : "/home/slam-emix/Datasets/BACK_END/2D/INTEL/SPOILED_DATA/50/06.g2o"
ground_truth : "/home/slam-emix/Datasets/BACK_END/2D/INTEL/GT.txt"
output : "res.txt"
canonic_inliers : 256
max_iters: 1000
inlier_th: 0.9
alpha: 0.99
