name : "INTEL"
dataset : "/home/slamemix/Data/RobustSLAM/2D/INTEL/SPOILED_DATA/80/01.g2o"
ground_truth : "/home/slamemix/Data/RobustSLAM/2D/INTEL/GT.txt"
output : "res.txt"
canonic_inliers : 256
max_iters: 30
inlier_th: 0.95
switch_prior: 10.0
maxmix_weight: 1e-1
nu_constraint: 0.95
nu_nullHypothesis: 1e-5
batch_size: 5